-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 08:49:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cinema` ;

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movie` ;

CREATE TABLE IF NOT EXISTS `Movie` (
  `id Movie` INT NOT NULL AUTO_INCREMENT,
  `Movie_titel` VARCHAR(45) NULL,
  `time` DATE NULL,
  `Movie_poster` VARCHAR(45) NULL,
  PRIMARY KEY (`id Movie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Saal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Saal` ;

CREATE TABLE IF NOT EXISTS `Saal` (
  `idSaal` INT NOT NULL AUTO_INCREMENT,
  `Saal` INT NULL,
  `fk_movieid` INT NOT NULL,
  `Sitz_id Sitz` INT NOT NULL,
  PRIMARY KEY (`idSaal`, `Sitz_id Sitz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sitz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sitz` ;

CREATE TABLE IF NOT EXISTS `Sitz` (
  `id Sitz` INT NOT NULL AUTO_INCREMENT,
  `Sitz_row` INT NOT NULL,
  `sitz_nummber` INT NOT NULL,
  `reservirt` TINYINT(1) NULL,
  PRIMARY KEY (`id Sitz`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
